# Generated by Django 3.0.5 on 2021-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210120_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tag_recipe', to='recipes.Tag'),
        ),
    ]
